
DROP TABLE IF EXISTS answer_attempts CASCADE;
CREATE TABLE answer_attempts (
  id SERIAL PRIMARY KEY NOT NULL,
  answer_id INTEGER REFERENCES answers(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
